language: objective-c
osx_image: xcode9.4
xcode_project: WeatherReport.xcodeproj
xcode_scheme: WeatherReport
xcode_sdk: iphonesimulator11.4
before_install: gem install bundler
notifications:
email: false
branches:
only:
- master
